# Source: jxl-boot/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jxl-boot
  # name: jxl-boot
  labels:
    helm.sh/chart: jxl-boot-0.1.0
    app.kubernetes.io/name: jxl-boot
    app.kubernetes.io/instance: myrel
    app.kubernetes.io/version: "0.0.88"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/jenkinsXaccessToS3
    foo: bar
    eks.amazonaws.com/role-arn: arn:aws:iam::myproject:role/mycluster-jx-jxl-boot
