{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jxl-boot
  # name: {{ include "jxl-boot.serviceAccountName" . }}
  labels:
    {{- include "jxl-boot.labels" . | nindent 4 }}
  annotations:
{{- if .Values.serviceAccount.annotations }}
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- if eq .Values.jxRequirements.cluster.provider "eks" }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.jxRequirements.cluster.project }}:role/{{ .Values.jxRequirements.cluster.clusterName }}-{{ .Values.jxRequirements.cluster.namespace }}-jxl-boot
{{- end }}
{{- if eq .Values.jxRequirements.cluster.provider "gke" }}
    iam.gke.io/gcp-service-account: "{{ .Values.jxRequirements.cluster.clusterName }}-jb@{{ .Values.jxRequirements.cluster.project }}.iam.gserviceaccount.com"
{{- end }}
{{- end -}}
